print("\nComplete el formulario.")
nombre = input("Nombre:")
comision = input("Comision:")
asignatura = input("Asinatura:")
docente = input("Docente:")
presentismo = input("Presente (si o no):")
print("\nSus datos son:")
print("Nombre:",nombre)
print("Comision:",comision)
print("Asinatura:",asignatura)
print("Docente:",docente)
print("Presente (si o no):",presentismo)